# fly.toml app configuration file generated for firecrawl-scraper-js-wispy-lake-7348 on 2024-10-25T16:14:54+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'firecrawl-scraper-js-wispy-lake-7348'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '30s'

[build]

[env]
  HOST = '0.0.0.0'
  PORT = '8080'

[processes]
  app = 'node --max-old-space-size=8192 dist/src/index.js'
  worker = 'node --max-old-space-size=8192 dist/src/services/queue-worker.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '15s'
    grace_period = '20s'
    method = 'GET'
    path = '/'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 8080
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    soft_limit = 200

[[vm]]
  size = 'performance-1x'
  processes = ['app']
